package com.demo.po;

import java.util.Date;

public class Leader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.formFillingMan
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String formfillingman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.linkTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String linktel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.leaderName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String leadername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String folk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String pol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String edu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.degree
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String managejob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.memo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.serDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date serdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.leaveDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date leavedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_leader.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String yearly;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.id
     *
     * @return the value of t_d0_leader.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.id
     *
     * @param id the value for t_d0_leader.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.orgId
     *
     * @return the value of t_d0_leader.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.orgId
     *
     * @param orgid the value for t_d0_leader.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.orgName
     *
     * @return the value of t_d0_leader.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.orgName
     *
     * @param orgname the value for t_d0_leader.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.orgNo
     *
     * @return the value of t_d0_leader.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.orgNo
     *
     * @param orgno the value for t_d0_leader.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.orgCode
     *
     * @return the value of t_d0_leader.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.orgCode
     *
     * @param orgcode the value for t_d0_leader.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.formFillingMan
     *
     * @return the value of t_d0_leader.formFillingMan
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getFormfillingman() {
        return formfillingman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.formFillingMan
     *
     * @param formfillingman the value for t_d0_leader.formFillingMan
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFormfillingman(String formfillingman) {
        this.formfillingman = formfillingman == null ? null : formfillingman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.linkTel
     *
     * @return the value of t_d0_leader.linkTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.linkTel
     *
     * @param linktel the value for t_d0_leader.linkTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel == null ? null : linktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.leaderName
     *
     * @return the value of t_d0_leader.leaderName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getLeadername() {
        return leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.leaderName
     *
     * @param leadername the value for t_d0_leader.leaderName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setLeadername(String leadername) {
        this.leadername = leadername == null ? null : leadername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.gender
     *
     * @return the value of t_d0_leader.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.gender
     *
     * @param gender the value for t_d0_leader.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.folk
     *
     * @return the value of t_d0_leader.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getFolk() {
        return folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.folk
     *
     * @param folk the value for t_d0_leader.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFolk(String folk) {
        this.folk = folk == null ? null : folk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.birthDate
     *
     * @return the value of t_d0_leader.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.birthDate
     *
     * @param birthdate the value for t_d0_leader.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.pol
     *
     * @return the value of t_d0_leader.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getPol() {
        return pol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.pol
     *
     * @param pol the value for t_d0_leader.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPol(String pol) {
        this.pol = pol == null ? null : pol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.edu
     *
     * @return the value of t_d0_leader.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.edu
     *
     * @param edu the value for t_d0_leader.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.degree
     *
     * @return the value of t_d0_leader.degree
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.degree
     *
     * @param degree the value for t_d0_leader.degree
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.manageJob
     *
     * @return the value of t_d0_leader.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getManagejob() {
        return managejob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.manageJob
     *
     * @param managejob the value for t_d0_leader.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setManagejob(String managejob) {
        this.managejob = managejob == null ? null : managejob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.title
     *
     * @return the value of t_d0_leader.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.title
     *
     * @param title the value for t_d0_leader.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.memo
     *
     * @return the value of t_d0_leader.memo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.memo
     *
     * @param memo the value for t_d0_leader.memo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.serDate
     *
     * @return the value of t_d0_leader.serDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getSerdate() {
        return serdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.serDate
     *
     * @param serdate the value for t_d0_leader.serDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setSerdate(Date serdate) {
        this.serdate = serdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.leaveDate
     *
     * @return the value of t_d0_leader.leaveDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.leaveDate
     *
     * @param leavedate the value for t_d0_leader.leaveDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_leader.yearly
     *
     * @return the value of t_d0_leader.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getYearly() {
        return yearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_leader.yearly
     *
     * @param yearly the value for t_d0_leader.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setYearly(String yearly) {
        this.yearly = yearly == null ? null : yearly.trim();
    }
}