package com.demo.po;

public class Orgattached {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.onworkerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer onworkernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.supervisorNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer supervisornum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.zbbNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short zbbnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.ifPublicmanage
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String ifpublicmanage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.retireNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer retirenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.officeBuildarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short officebuildarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.buildingOwnership
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String buildingownership;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.officeBuildingarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short officebuildingarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.businessDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short businessdivcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.funDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short fundivcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.orgCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short orgcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.equ3Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer equ3count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.equ2Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer equ2count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.equ1Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Integer equ1count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.busCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short buscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.rapidtestvehicleCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short rapidtestvehiclecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.motorCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short motorcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.cameraCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short cameracount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.videoCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short videocount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.copycatNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short copycatnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.computerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short computernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.notepadNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short notepadnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.serverCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short servercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.pbxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short pbxcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.faxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short faxcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.ohpCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short ohpcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String yearly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_orgattached.VRCOUNT
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Short vrcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.id
     *
     * @return the value of t_d0_orgattached.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.id
     *
     * @param id the value for t_d0_orgattached.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.orgId
     *
     * @return the value of t_d0_orgattached.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.orgId
     *
     * @param orgid the value for t_d0_orgattached.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.orgName
     *
     * @return the value of t_d0_orgattached.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.orgName
     *
     * @param orgname the value for t_d0_orgattached.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.orgNo
     *
     * @return the value of t_d0_orgattached.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.orgNo
     *
     * @param orgno the value for t_d0_orgattached.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.orgCode
     *
     * @return the value of t_d0_orgattached.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.orgCode
     *
     * @param orgcode the value for t_d0_orgattached.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.onworkerNum
     *
     * @return the value of t_d0_orgattached.onworkerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getOnworkernum() {
        return onworkernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.onworkerNum
     *
     * @param onworkernum the value for t_d0_orgattached.onworkerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOnworkernum(Integer onworkernum) {
        this.onworkernum = onworkernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.supervisorNum
     *
     * @return the value of t_d0_orgattached.supervisorNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getSupervisornum() {
        return supervisornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.supervisorNum
     *
     * @param supervisornum the value for t_d0_orgattached.supervisorNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setSupervisornum(Integer supervisornum) {
        this.supervisornum = supervisornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.zbbNum
     *
     * @return the value of t_d0_orgattached.zbbNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getZbbnum() {
        return zbbnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.zbbNum
     *
     * @param zbbnum the value for t_d0_orgattached.zbbNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setZbbnum(Short zbbnum) {
        this.zbbnum = zbbnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.ifPublicmanage
     *
     * @return the value of t_d0_orgattached.ifPublicmanage
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getIfpublicmanage() {
        return ifpublicmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.ifPublicmanage
     *
     * @param ifpublicmanage the value for t_d0_orgattached.ifPublicmanage
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setIfpublicmanage(String ifpublicmanage) {
        this.ifpublicmanage = ifpublicmanage == null ? null : ifpublicmanage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.retireNum
     *
     * @return the value of t_d0_orgattached.retireNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getRetirenum() {
        return retirenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.retireNum
     *
     * @param retirenum the value for t_d0_orgattached.retireNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setRetirenum(Integer retirenum) {
        this.retirenum = retirenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.officeBuildarea
     *
     * @return the value of t_d0_orgattached.officeBuildarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getOfficebuildarea() {
        return officebuildarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.officeBuildarea
     *
     * @param officebuildarea the value for t_d0_orgattached.officeBuildarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOfficebuildarea(Short officebuildarea) {
        this.officebuildarea = officebuildarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.buildingOwnership
     *
     * @return the value of t_d0_orgattached.buildingOwnership
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getBuildingownership() {
        return buildingownership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.buildingOwnership
     *
     * @param buildingownership the value for t_d0_orgattached.buildingOwnership
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBuildingownership(String buildingownership) {
        this.buildingownership = buildingownership == null ? null : buildingownership.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.officeBuildingarea
     *
     * @return the value of t_d0_orgattached.officeBuildingarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getOfficebuildingarea() {
        return officebuildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.officeBuildingarea
     *
     * @param officebuildingarea the value for t_d0_orgattached.officeBuildingarea
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOfficebuildingarea(Short officebuildingarea) {
        this.officebuildingarea = officebuildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.businessDivCount
     *
     * @return the value of t_d0_orgattached.businessDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getBusinessdivcount() {
        return businessdivcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.businessDivCount
     *
     * @param businessdivcount the value for t_d0_orgattached.businessDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBusinessdivcount(Short businessdivcount) {
        this.businessdivcount = businessdivcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.funDivCount
     *
     * @return the value of t_d0_orgattached.funDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getFundivcount() {
        return fundivcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.funDivCount
     *
     * @param fundivcount the value for t_d0_orgattached.funDivCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFundivcount(Short fundivcount) {
        this.fundivcount = fundivcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.orgCount
     *
     * @return the value of t_d0_orgattached.orgCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getOrgcount() {
        return orgcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.orgCount
     *
     * @param orgcount the value for t_d0_orgattached.orgCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgcount(Short orgcount) {
        this.orgcount = orgcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.equ3Count
     *
     * @return the value of t_d0_orgattached.equ3Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getEqu3count() {
        return equ3count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.equ3Count
     *
     * @param equ3count the value for t_d0_orgattached.equ3Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEqu3count(Integer equ3count) {
        this.equ3count = equ3count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.equ2Count
     *
     * @return the value of t_d0_orgattached.equ2Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getEqu2count() {
        return equ2count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.equ2Count
     *
     * @param equ2count the value for t_d0_orgattached.equ2Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEqu2count(Integer equ2count) {
        this.equ2count = equ2count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.equ1Count
     *
     * @return the value of t_d0_orgattached.equ1Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Integer getEqu1count() {
        return equ1count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.equ1Count
     *
     * @param equ1count the value for t_d0_orgattached.equ1Count
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEqu1count(Integer equ1count) {
        this.equ1count = equ1count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.busCount
     *
     * @return the value of t_d0_orgattached.busCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getBuscount() {
        return buscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.busCount
     *
     * @param buscount the value for t_d0_orgattached.busCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBuscount(Short buscount) {
        this.buscount = buscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.rapidtestvehicleCount
     *
     * @return the value of t_d0_orgattached.rapidtestvehicleCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getRapidtestvehiclecount() {
        return rapidtestvehiclecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.rapidtestvehicleCount
     *
     * @param rapidtestvehiclecount the value for t_d0_orgattached.rapidtestvehicleCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setRapidtestvehiclecount(Short rapidtestvehiclecount) {
        this.rapidtestvehiclecount = rapidtestvehiclecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.motorCount
     *
     * @return the value of t_d0_orgattached.motorCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getMotorcount() {
        return motorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.motorCount
     *
     * @param motorcount the value for t_d0_orgattached.motorCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setMotorcount(Short motorcount) {
        this.motorcount = motorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.cameraCount
     *
     * @return the value of t_d0_orgattached.cameraCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getCameracount() {
        return cameracount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.cameraCount
     *
     * @param cameracount the value for t_d0_orgattached.cameraCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setCameracount(Short cameracount) {
        this.cameracount = cameracount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.videoCount
     *
     * @return the value of t_d0_orgattached.videoCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getVideocount() {
        return videocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.videoCount
     *
     * @param videocount the value for t_d0_orgattached.videoCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setVideocount(Short videocount) {
        this.videocount = videocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.copycatNum
     *
     * @return the value of t_d0_orgattached.copycatNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getCopycatnum() {
        return copycatnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.copycatNum
     *
     * @param copycatnum the value for t_d0_orgattached.copycatNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setCopycatnum(Short copycatnum) {
        this.copycatnum = copycatnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.computerNum
     *
     * @return the value of t_d0_orgattached.computerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getComputernum() {
        return computernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.computerNum
     *
     * @param computernum the value for t_d0_orgattached.computerNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setComputernum(Short computernum) {
        this.computernum = computernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.notepadNum
     *
     * @return the value of t_d0_orgattached.notepadNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getNotepadnum() {
        return notepadnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.notepadNum
     *
     * @param notepadnum the value for t_d0_orgattached.notepadNum
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setNotepadnum(Short notepadnum) {
        this.notepadnum = notepadnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.serverCount
     *
     * @return the value of t_d0_orgattached.serverCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getServercount() {
        return servercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.serverCount
     *
     * @param servercount the value for t_d0_orgattached.serverCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setServercount(Short servercount) {
        this.servercount = servercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.pbxCount
     *
     * @return the value of t_d0_orgattached.pbxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getPbxcount() {
        return pbxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.pbxCount
     *
     * @param pbxcount the value for t_d0_orgattached.pbxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPbxcount(Short pbxcount) {
        this.pbxcount = pbxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.faxCount
     *
     * @return the value of t_d0_orgattached.faxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getFaxcount() {
        return faxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.faxCount
     *
     * @param faxcount the value for t_d0_orgattached.faxCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFaxcount(Short faxcount) {
        this.faxcount = faxcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.ohpCount
     *
     * @return the value of t_d0_orgattached.ohpCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getOhpcount() {
        return ohpcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.ohpCount
     *
     * @param ohpcount the value for t_d0_orgattached.ohpCount
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOhpcount(Short ohpcount) {
        this.ohpcount = ohpcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.yearly
     *
     * @return the value of t_d0_orgattached.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getYearly() {
        return yearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.yearly
     *
     * @param yearly the value for t_d0_orgattached.yearly
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setYearly(String yearly) {
        this.yearly = yearly == null ? null : yearly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_orgattached.VRCOUNT
     *
     * @return the value of t_d0_orgattached.VRCOUNT
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Short getVrcount() {
        return vrcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_orgattached.VRCOUNT
     *
     * @param vrcount the value for t_d0_orgattached.VRCOUNT
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setVrcount(Short vrcount) {
        this.vrcount = vrcount;
    }
}