package com.demo.po;

import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.exeType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String exetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.areaCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.linkAdd
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String linkadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.listingDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date listingdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.standaloneDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date standalonedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.areaType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String areatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.zbbdocDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date zbbdocdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.orgLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orglevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.orgPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgpro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_organization.ZIPCODE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String zipcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.id
     *
     * @return the value of t_d0_organization.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.id
     *
     * @param id the value for t_d0_organization.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.orgNo
     *
     * @return the value of t_d0_organization.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.orgNo
     *
     * @param orgno the value for t_d0_organization.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.orgCode
     *
     * @return the value of t_d0_organization.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.orgCode
     *
     * @param orgcode the value for t_d0_organization.orgCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.orgName
     *
     * @return the value of t_d0_organization.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.orgName
     *
     * @param orgname the value for t_d0_organization.orgName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.exeType
     *
     * @return the value of t_d0_organization.exeType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getExetype() {
        return exetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.exeType
     *
     * @param exetype the value for t_d0_organization.exeType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setExetype(String exetype) {
        this.exetype = exetype == null ? null : exetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.areaCode
     *
     * @return the value of t_d0_organization.areaCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.areaCode
     *
     * @param areacode the value for t_d0_organization.areaCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.linkAdd
     *
     * @return the value of t_d0_organization.linkAdd
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getLinkadd() {
        return linkadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.linkAdd
     *
     * @param linkadd the value for t_d0_organization.linkAdd
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setLinkadd(String linkadd) {
        this.linkadd = linkadd == null ? null : linkadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.listingDate
     *
     * @return the value of t_d0_organization.listingDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getListingdate() {
        return listingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.listingDate
     *
     * @param listingdate the value for t_d0_organization.listingDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setListingdate(Date listingdate) {
        this.listingdate = listingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.standaloneDate
     *
     * @return the value of t_d0_organization.standaloneDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getStandalonedate() {
        return standalonedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.standaloneDate
     *
     * @param standalonedate the value for t_d0_organization.standaloneDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setStandalonedate(Date standalonedate) {
        this.standalonedate = standalonedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.areaType
     *
     * @return the value of t_d0_organization.areaType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getAreatype() {
        return areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.areaType
     *
     * @param areatype the value for t_d0_organization.areaType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setAreatype(String areatype) {
        this.areatype = areatype == null ? null : areatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.zbbdocDate
     *
     * @return the value of t_d0_organization.zbbdocDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getZbbdocdate() {
        return zbbdocdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.zbbdocDate
     *
     * @param zbbdocdate the value for t_d0_organization.zbbdocDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setZbbdocdate(Date zbbdocdate) {
        this.zbbdocdate = zbbdocdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.orgLevel
     *
     * @return the value of t_d0_organization.orgLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrglevel() {
        return orglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.orgLevel
     *
     * @param orglevel the value for t_d0_organization.orgLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrglevel(String orglevel) {
        this.orglevel = orglevel == null ? null : orglevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.orgPro
     *
     * @return the value of t_d0_organization.orgPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgpro() {
        return orgpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.orgPro
     *
     * @param orgpro the value for t_d0_organization.orgPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgpro(String orgpro) {
        this.orgpro = orgpro == null ? null : orgpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_organization.ZIPCODE
     *
     * @return the value of t_d0_organization.ZIPCODE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_organization.ZIPCODE
     *
     * @param zipcode the value for t_d0_organization.ZIPCODE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }
}