package com.demo.po;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String divcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.divNameCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String divnamecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.divName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String divname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.ifSub
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String ifsub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.dutyTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String dutytel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.fax
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.divRoomNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String divroomno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_section.EXETYPE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String exetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.id
     *
     * @return the value of t_d0_section.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.id
     *
     * @param id the value for t_d0_section.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.orgId
     *
     * @return the value of t_d0_section.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.orgId
     *
     * @param orgid the value for t_d0_section.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.orgNo
     *
     * @return the value of t_d0_section.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.orgNo
     *
     * @param orgno the value for t_d0_section.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.divCode
     *
     * @return the value of t_d0_section.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDivcode() {
        return divcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.divCode
     *
     * @param divcode the value for t_d0_section.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDivcode(String divcode) {
        this.divcode = divcode == null ? null : divcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.divNameCode
     *
     * @return the value of t_d0_section.divNameCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDivnamecode() {
        return divnamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.divNameCode
     *
     * @param divnamecode the value for t_d0_section.divNameCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDivnamecode(String divnamecode) {
        this.divnamecode = divnamecode == null ? null : divnamecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.divName
     *
     * @return the value of t_d0_section.divName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDivname() {
        return divname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.divName
     *
     * @param divname the value for t_d0_section.divName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDivname(String divname) {
        this.divname = divname == null ? null : divname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.ifSub
     *
     * @return the value of t_d0_section.ifSub
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getIfsub() {
        return ifsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.ifSub
     *
     * @param ifsub the value for t_d0_section.ifSub
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setIfsub(String ifsub) {
        this.ifsub = ifsub == null ? null : ifsub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.dutyTel
     *
     * @return the value of t_d0_section.dutyTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDutytel() {
        return dutytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.dutyTel
     *
     * @param dutytel the value for t_d0_section.dutyTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDutytel(String dutytel) {
        this.dutytel = dutytel == null ? null : dutytel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.fax
     *
     * @return the value of t_d0_section.fax
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.fax
     *
     * @param fax the value for t_d0_section.fax
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.divRoomNo
     *
     * @return the value of t_d0_section.divRoomNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDivroomno() {
        return divroomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.divRoomNo
     *
     * @param divroomno the value for t_d0_section.divRoomNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDivroomno(String divroomno) {
        this.divroomno = divroomno == null ? null : divroomno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_section.EXETYPE
     *
     * @return the value of t_d0_section.EXETYPE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getExetype() {
        return exetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_section.EXETYPE
     *
     * @param exetype the value for t_d0_section.EXETYPE
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setExetype(String exetype) {
        this.exetype = exetype == null ? null : exetype.trim();
    }
}