package com.demo.po;

import java.util.Date;

public class Stuff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.sectionId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String sectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String divcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.repManName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String repmanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String folk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String pol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.mobile
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.workTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String worktel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.email
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String edu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.graCollege
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String gracollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.choiceSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String choicespe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.spe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String spe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.beforeSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String beforespe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.beginWorkDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date beginworkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String managejob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.jobLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String joblevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.getInDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date getindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.perPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String perpro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.perType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String pertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.enfCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String enfcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.getCardDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date getcarddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.healthPerNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String healthperno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.getQuaDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date getquadate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.healthCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String healthcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.cardDay
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private Date cardday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.ifStaffPer
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String ifstaffper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_stuff.perCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    private String percode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.id
     *
     * @return the value of t_d0_stuff.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.id
     *
     * @param id the value for t_d0_stuff.id
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.sectionId
     *
     * @return the value of t_d0_stuff.sectionId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.sectionId
     *
     * @param sectionid the value for t_d0_stuff.sectionId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setSectionid(String sectionid) {
        this.sectionid = sectionid == null ? null : sectionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.divCode
     *
     * @return the value of t_d0_stuff.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getDivcode() {
        return divcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.divCode
     *
     * @param divcode the value for t_d0_stuff.divCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setDivcode(String divcode) {
        this.divcode = divcode == null ? null : divcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.orgId
     *
     * @return the value of t_d0_stuff.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.orgId
     *
     * @param orgid the value for t_d0_stuff.orgId
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.orgNo
     *
     * @return the value of t_d0_stuff.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.orgNo
     *
     * @param orgno the value for t_d0_stuff.orgNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.repManName
     *
     * @return the value of t_d0_stuff.repManName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getRepmanname() {
        return repmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.repManName
     *
     * @param repmanname the value for t_d0_stuff.repManName
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setRepmanname(String repmanname) {
        this.repmanname = repmanname == null ? null : repmanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.gender
     *
     * @return the value of t_d0_stuff.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.gender
     *
     * @param gender the value for t_d0_stuff.gender
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.birthDate
     *
     * @return the value of t_d0_stuff.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.birthDate
     *
     * @param birthdate the value for t_d0_stuff.birthDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.folk
     *
     * @return the value of t_d0_stuff.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getFolk() {
        return folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.folk
     *
     * @param folk the value for t_d0_stuff.folk
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setFolk(String folk) {
        this.folk = folk == null ? null : folk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.pol
     *
     * @return the value of t_d0_stuff.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getPol() {
        return pol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.pol
     *
     * @param pol the value for t_d0_stuff.pol
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPol(String pol) {
        this.pol = pol == null ? null : pol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.mobile
     *
     * @return the value of t_d0_stuff.mobile
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.mobile
     *
     * @param mobile the value for t_d0_stuff.mobile
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.workTel
     *
     * @return the value of t_d0_stuff.workTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getWorktel() {
        return worktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.workTel
     *
     * @param worktel the value for t_d0_stuff.workTel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setWorktel(String worktel) {
        this.worktel = worktel == null ? null : worktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.email
     *
     * @return the value of t_d0_stuff.email
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.email
     *
     * @param email the value for t_d0_stuff.email
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.edu
     *
     * @return the value of t_d0_stuff.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.edu
     *
     * @param edu the value for t_d0_stuff.edu
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.graCollege
     *
     * @return the value of t_d0_stuff.graCollege
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getGracollege() {
        return gracollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.graCollege
     *
     * @param gracollege the value for t_d0_stuff.graCollege
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGracollege(String gracollege) {
        this.gracollege = gracollege == null ? null : gracollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.choiceSpe
     *
     * @return the value of t_d0_stuff.choiceSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getChoicespe() {
        return choicespe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.choiceSpe
     *
     * @param choicespe the value for t_d0_stuff.choiceSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setChoicespe(String choicespe) {
        this.choicespe = choicespe == null ? null : choicespe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.spe
     *
     * @return the value of t_d0_stuff.spe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getSpe() {
        return spe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.spe
     *
     * @param spe the value for t_d0_stuff.spe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setSpe(String spe) {
        this.spe = spe == null ? null : spe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.beforeSpe
     *
     * @return the value of t_d0_stuff.beforeSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getBeforespe() {
        return beforespe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.beforeSpe
     *
     * @param beforespe the value for t_d0_stuff.beforeSpe
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBeforespe(String beforespe) {
        this.beforespe = beforespe == null ? null : beforespe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.beginWorkDate
     *
     * @return the value of t_d0_stuff.beginWorkDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getBeginworkdate() {
        return beginworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.beginWorkDate
     *
     * @param beginworkdate the value for t_d0_stuff.beginWorkDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setBeginworkdate(Date beginworkdate) {
        this.beginworkdate = beginworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.manageJob
     *
     * @return the value of t_d0_stuff.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getManagejob() {
        return managejob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.manageJob
     *
     * @param managejob the value for t_d0_stuff.manageJob
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setManagejob(String managejob) {
        this.managejob = managejob == null ? null : managejob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.jobLevel
     *
     * @return the value of t_d0_stuff.jobLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getJoblevel() {
        return joblevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.jobLevel
     *
     * @param joblevel the value for t_d0_stuff.jobLevel
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setJoblevel(String joblevel) {
        this.joblevel = joblevel == null ? null : joblevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.title
     *
     * @return the value of t_d0_stuff.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.title
     *
     * @param title the value for t_d0_stuff.title
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.getInDate
     *
     * @return the value of t_d0_stuff.getInDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getGetindate() {
        return getindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.getInDate
     *
     * @param getindate the value for t_d0_stuff.getInDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGetindate(Date getindate) {
        this.getindate = getindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.perPro
     *
     * @return the value of t_d0_stuff.perPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getPerpro() {
        return perpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.perPro
     *
     * @param perpro the value for t_d0_stuff.perPro
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPerpro(String perpro) {
        this.perpro = perpro == null ? null : perpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.perType
     *
     * @return the value of t_d0_stuff.perType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getPertype() {
        return pertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.perType
     *
     * @param pertype the value for t_d0_stuff.perType
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPertype(String pertype) {
        this.pertype = pertype == null ? null : pertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.enfCardNo
     *
     * @return the value of t_d0_stuff.enfCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getEnfcardno() {
        return enfcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.enfCardNo
     *
     * @param enfcardno the value for t_d0_stuff.enfCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setEnfcardno(String enfcardno) {
        this.enfcardno = enfcardno == null ? null : enfcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.getCardDate
     *
     * @return the value of t_d0_stuff.getCardDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getGetcarddate() {
        return getcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.getCardDate
     *
     * @param getcarddate the value for t_d0_stuff.getCardDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGetcarddate(Date getcarddate) {
        this.getcarddate = getcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.healthPerNo
     *
     * @return the value of t_d0_stuff.healthPerNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getHealthperno() {
        return healthperno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.healthPerNo
     *
     * @param healthperno the value for t_d0_stuff.healthPerNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setHealthperno(String healthperno) {
        this.healthperno = healthperno == null ? null : healthperno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.getQuaDate
     *
     * @return the value of t_d0_stuff.getQuaDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getGetquadate() {
        return getquadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.getQuaDate
     *
     * @param getquadate the value for t_d0_stuff.getQuaDate
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setGetquadate(Date getquadate) {
        this.getquadate = getquadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.healthCardNo
     *
     * @return the value of t_d0_stuff.healthCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getHealthcardno() {
        return healthcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.healthCardNo
     *
     * @param healthcardno the value for t_d0_stuff.healthCardNo
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setHealthcardno(String healthcardno) {
        this.healthcardno = healthcardno == null ? null : healthcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.cardDay
     *
     * @return the value of t_d0_stuff.cardDay
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public Date getCardday() {
        return cardday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.cardDay
     *
     * @param cardday the value for t_d0_stuff.cardDay
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setCardday(Date cardday) {
        this.cardday = cardday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.ifStaffPer
     *
     * @return the value of t_d0_stuff.ifStaffPer
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getIfstaffper() {
        return ifstaffper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.ifStaffPer
     *
     * @param ifstaffper the value for t_d0_stuff.ifStaffPer
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setIfstaffper(String ifstaffper) {
        this.ifstaffper = ifstaffper == null ? null : ifstaffper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_stuff.perCode
     *
     * @return the value of t_d0_stuff.perCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_stuff.perCode
     *
     * @param percode the value for t_d0_stuff.perCode
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    public void setPercode(String percode) {
        this.percode = percode == null ? null : percode.trim();
    }
}