package com.demo.dao;


import com.demo.po.Fund;

public interface FundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Fund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_fund
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Fund record);
}