package com.demo.dao;


import com.demo.po.Leader;

public interface LeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Leader selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_leader
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Leader record);
}