package com.demo.dao;


import com.demo.po.Orgattached;

public interface OrgattachedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Orgattached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Orgattached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Orgattached selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Orgattached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_orgattached
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Orgattached record);
}