package com.demo.dao;


import com.demo.po.Organization;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Organization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_organization
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Organization record);
}