package com.demo.dao;


import com.demo.po.Section;

public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Section selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_section
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Section record);
}