package com.demo.dao;


import com.demo.po.Stuff;

public interface StuffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insert(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int insertSelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    Stuff selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d0_stuff
     *
     * @mbg.generated Mon Jun 03 17:05:21 GMT+08:00 2019
     */
    int updateByPrimaryKey(Stuff record);
}